FROM	alpine:latest

LABEL	maintainer="aurbuche <aurbuche@student.42lyon.fr>"

#Packages
RUN		apk upgrade
RUN		apk update
RUN		apk add openrc vim --no-cache
RUN		apk add mysql mysql-client



RUN		printf "MySQL is install!"
